import { AlertTriangle, Info, HelpCircle } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Business } from '@/types/business';
import { validateBusiness, ValidationError } from '@/lib/validation';

interface NeedAttentionBannerProps {
  pendingBusinesses: Business[];
  showAsyncInfo?: boolean;
}

interface IssueCategory {
  label: string;
  count: number;
  description: string;
  icon: React.ReactNode;
}

const NeedAttentionBanner = ({ pendingBusinesses, showAsyncInfo = false }: NeedAttentionBannerProps) => {
  if (pendingBusinesses.length === 0) return null;

  // Analyze all pending businesses to categorize issues
  const analyzeIssues = (): IssueCategory[] => {
    const issues: IssueCategory[] = [];
    
    let missingRequiredFields = 0;
    let autoGeneratedStoreCodes = 0;
    let asyncLocations = 0;
    let validationErrors = 0;

    const fieldIssues: Record<string, number> = {};

    pendingBusinesses.forEach((business) => {
      // Check for auto-generated store code
      if (business.storeCode?.match(/^STORE\d+/)) {
        autoGeneratedStoreCodes++;
      }

      // Check for async locations
      if ((business as any).is_async === true) {
        asyncLocations++;
      }

      // Run validation and categorize errors
      const { errors } = validateBusiness(business);
      if (errors.length > 0) {
        validationErrors++;
        errors.forEach((error) => {
          const fieldLabel = error.field.replace(/([A-Z])/g, ' $1').trim();
          fieldIssues[fieldLabel] = (fieldIssues[fieldLabel] || 0) + 1;
        });
      }

      // Check for missing essential fields
      const essentialFields = ['businessName', 'addressLine1', 'country', 'primaryCategory'];
      essentialFields.forEach((field) => {
        if (!business[field as keyof Business] || String(business[field as keyof Business]).trim() === '') {
          missingRequiredFields++;
        }
      });
    });

    if (autoGeneratedStoreCodes > 0) {
      issues.push({
        label: 'Auto-generated Store Codes',
        count: autoGeneratedStoreCodes,
        description: 'These locations have temporary store codes (STORE123...) that should be replaced with your actual store identifiers.',
        icon: <AlertTriangle className="w-4 h-4 text-amber-600" />,
      });
    }

    if (validationErrors > 0) {
      issues.push({
        label: 'Validation Errors',
        count: validationErrors,
        description: 'These locations have data validation issues that prevent them from being published.',
        icon: <AlertTriangle className="w-4 h-4 text-destructive" />,
      });
    }

    if (asyncLocations > 0 && showAsyncInfo) {
      issues.push({
        label: 'Out of Sync with API',
        count: asyncLocations,
        description: 'These locations exist in Jasoner but are not currently present in the external API feed. They may have been removed from the source system.',
        icon: <Info className="w-4 h-4 text-blue-600" />,
      });
    }

    return issues;
  };

  const issues = analyzeIssues();

  // Get the top field-level issues
  const getTopFieldIssues = () => {
    const fieldCounts: Record<string, number> = {};
    
    pendingBusinesses.forEach((business) => {
      const { errors } = validateBusiness(business);
      errors.forEach((error) => {
        const label = getFieldLabel(error.field);
        fieldCounts[label] = (fieldCounts[label] || 0) + 1;
      });
    });

    return Object.entries(fieldCounts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 5);
  };

  const getFieldLabel = (field: string): string => {
    const labels: Record<string, string> = {
      storeCode: 'Store Code',
      businessName: 'Business Name',
      addressLine1: 'Address',
      country: 'Country',
      primaryCategory: 'Category',
      fromTheBusiness: 'Description',
      latitude: 'Latitude',
      longitude: 'Longitude',
    };
    return labels[field] || field.replace(/([A-Z])/g, ' $1').trim();
  };

  const topFieldIssues = getTopFieldIssues();

  return (
    <Card className="bg-amber-50 border-amber-200 mb-4">
      <CardContent className="py-3">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-5 h-5 text-amber-600 mt-0.5 flex-shrink-0" />
            <div className="space-y-1">
              <p className="text-sm font-medium text-amber-800">
                {pendingBusinesses.length} location{pendingBusinesses.length !== 1 ? 's' : ''} need{pendingBusinesses.length === 1 ? 's' : ''} attention
              </p>
              <p className="text-xs text-amber-700">
                These locations are missing required information or have validation issues. They won't be published until fixed.
              </p>
            </div>
          </div>
          
          <Dialog>
            <DialogTrigger asChild>
              <Button variant="outline" size="sm" className="flex items-center gap-1.5 border-amber-300 text-amber-800 hover:bg-amber-100">
                <HelpCircle className="w-4 h-4" />
                <span className="hidden sm:inline">View Details</span>
                <span className="sm:hidden">Details</span>
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-lg">
              <DialogHeader>
                <DialogTitle className="flex items-center gap-2">
                  <AlertTriangle className="w-5 h-5 text-amber-600" />
                  Why These Locations Need Attention
                </DialogTitle>
              </DialogHeader>
              <ScrollArea className="max-h-[60vh]">
                <div className="space-y-4 pr-4">
                  {/* Issue Categories */}
                  {issues.length > 0 && (
                    <div className="space-y-3">
                      <h4 className="font-medium text-sm">Issue Summary:</h4>
                      {issues.map((issue, idx) => (
                        <div key={idx} className="flex items-start gap-3 p-3 bg-muted rounded-md">
                          {issue.icon}
                          <div className="flex-1">
                            <div className="flex items-center gap-2">
                              <span className="font-medium text-sm">{issue.label}</span>
                              <Badge variant="secondary" className="text-xs">{issue.count}</Badge>
                            </div>
                            <p className="text-xs text-muted-foreground mt-1">{issue.description}</p>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}

                  {/* Top Field Issues */}
                  {topFieldIssues.length > 0 && (
                    <div className="space-y-3">
                      <h4 className="font-medium text-sm">Most Common Field Issues:</h4>
                      <div className="space-y-2">
                        {topFieldIssues.map(([field, count], idx) => (
                          <div key={idx} className="flex items-center justify-between p-2 bg-destructive/10 rounded-md">
                            <span className="text-sm text-destructive">{field}</span>
                            <Badge variant="destructive" className="text-xs">{count} location{count !== 1 ? 's' : ''}</Badge>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  {/* How to fix */}
                  <div className="space-y-3 pt-2 border-t">
                    <h4 className="font-medium text-sm">How to Fix:</h4>
                    <ul className="space-y-2 text-sm text-muted-foreground">
                      <li className="flex items-start gap-2">
                        <span className="text-primary">1.</span>
                        <span>Click on a location to edit it and see its specific validation errors.</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-primary">2.</span>
                        <span>Fill in all required fields marked with asterisks (*) or highlighted in red.</span>
                      </li>
                      <li className="flex items-start gap-2">
                        <span className="text-primary">3.</span>
                        <span>Save the changes. Once all issues are resolved, the location will move to "Active".</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </ScrollArea>
            </DialogContent>
          </Dialog>
        </div>
      </CardContent>
    </Card>
  );
};

export default NeedAttentionBanner;
